name: CI

on:
  push:
    branches:
      - 'develop'
      - 'feature/**'
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.axaml'
  pull_request:
    branches:
      - 'develop'
      - 'feature/**'
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.axaml'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Setup .NET 3.1.x
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '3.1'

    - name: Run linter
      run: dotnet format --verify-no-changes

    - name: Restore dependencies
      run: dotnet restore

    - name: Build .NET Core 3.1
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
